create table if not exists public.products (
  id bigint generated by default as identity primary key,
  product_id text,
  product_code text not null unique,
  category text,
  width_cm text,
  length_cm text,
  size_cm text,
  area_m2 text,
  width_ft text,
  length_ft text,
  size_ft text,
  status text default 'active',
  source_tab text,
  source_row text,
  loaded_store_count integer default 0,
  loaded_stores text,
  sold_at text,
  sold_site text,
  customer_name text,
  customer_phone text,
  customer_address text,
  customer_contact_country text,
  note text,
  updated_at text
);

create index if not exists idx_products_product_code on public.products (product_code);
create index if not exists idx_products_status on public.products (status);
